global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "caatsm-app"
    static_configs:
      - targets: ["app:3002"]
  - job_name: "nats"
    metrics_path: /metrics
    static_configs:
      - targets: ["nats:8222"]

