// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/windy/caatsm-dashboard/views/layouts"
)

// Dashboard renders the realtime overview page.
func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"grid gap-6 md:grid-cols-2\"><div class=\"rounded-xl border border-slate-800 bg-slate-900/40 p-6 shadow-lg\"><h2 class=\"mb-4 text-lg font-medium text-slate-200\">Live Stream</h2><div class=\"h-72 overflow-y-auto rounded-lg border border-slate-800 bg-slate-950/60 p-4\" id=\"live-stream\" hx-ext=\"sse\" sse-connect=\"/api/stream\" sse-swap=\"message\"><p class=\"text-sm text-slate-500\">Waiting for telegrams...</p></div></div><div class=\"rounded-xl border border-slate-800 bg-slate-900/40 p-6 shadow-lg\"><h2 class=\"mb-4 text-lg font-medium text-slate-200\">Traffic Snapshot</h2><div class=\"grid gap-4\"><div class=\"rounded-lg border border-slate-800 bg-slate-950/60 p-4\"><p class=\"text-xs uppercase text-slate-500\">Total Messages (24h)</p><p class=\"mt-2 text-3xl font-semibold text-slate-100\" hx-get=\"/api/stats/total\" hx-trigger=\"load, every 30s\" hx-target=\"this\" hx-swap=\"innerHTML\">--</p></div><div class=\"rounded-lg border border-slate-800 bg-slate-950/60 p-4\"><p class=\"text-xs uppercase text-slate-500\">Priority Breakdown</p><div class=\"mt-3 space-y-2 text-sm text-slate-300\" hx-get=\"/api/stats/priority\" hx-trigger=\"load, every 45s\" hx-target=\"this\" hx-swap=\"innerHTML\"><p>Loading...</p></div></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Dashboard").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
